name: Reviewdog

on: pull_request

jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: go version
        id: go-ver
        run: |
          GO_VERSION=`sed -ne 's/^golang \(.*\)/\1/p' .tool-versions`

          echo "go version is ${GO_VERSION}"
          echo "::set-output name=version::${GO_VERSION}"

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.go-ver.outputs.version }}

      - name: Build linter
        run: |
          go build -o ml ./mylinter/cmd/mylinter

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Run Reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.MY_TOKEN }}
        run: |
          go vet -vettool ml ./... | reviewdog -f=golint -reporter=github-pr-review
